run:
  tests: true

linters:
  enable:
    - errname
    - gofmt
    - gofumpt
    - goimports
    - misspell
    - nilerr
    - predeclared
    - revive
    - thelper
    - unconvert
    - unparam
    - whitespace
